import 'package:flutter/material.dart';
import '../../widgets/navigation_drawer.dart';
import '../productTaskPage/models/product_task_module.dart';
import 'widgets/project_card.dart';
import 'models/project.dart';

class CreateProjectPage extends StatefulWidget {
  // Changed from StatelessWidget → StatefulWidget so we can
  // add projects at runtime and trigger rebuilds with setState
  const CreateProjectPage({super.key});

  @override
  State<CreateProjectPage> createState() => _CreateProjectPageState();
}

class _CreateProjectPageState extends State<CreateProjectPage> {

  // ── Sample groups for the demo projects ───────────────────────────────
  // In production these will be generated by the AI per-project instead
  // of being hard-coded here.
  static final _mobileDesignGroup = TaskGroup(name: 'Design', color: const Color(0xFF6366F1));
  static final _mobileDevGroup    = TaskGroup(name: 'Development', color: const Color(0xFF0EA5E9));
  static final _migrationGroup    = TaskGroup(name: 'Engineering', color: const Color(0xFF10B981));

  // ── Live project list — starts with sample data ──────────────────────────
  // Tasks are now real ProductTask objects, so each one supports status,
  // priority, group, due date, time tracking — the full feature set built
  // for the Product Launch page.
  late final List<Project> _projects = [
    Project(
      title: "Mobile App Redesign",
      deadline: DateTime.now().add(const Duration(days: 18)),
      groups: [_mobileDesignGroup, _mobileDevGroup],
      tasks: [
        ProductTask(title: "Wireframes", description: "Low-fi wireframes for all screens",
            dueDate: "May 2", status: "Done", priority: "Medium", progress: 1.0,
            group: _mobileDesignGroup, checklist: []),
        ProductTask(title: "Design system", description: "Shared components and tokens",
            dueDate: "May 5", status: "Done", priority: "High", progress: 1.0,
            group: _mobileDesignGroup, checklist: []),
        ProductTask(title: "Onboarding screens", description: "First-run user flow",
            dueDate: "May 8", status: "Done", priority: "Medium", progress: 1.0,
            group: _mobileDesignGroup, checklist: []),
        ProductTask(title: "Home screen", description: "Main dashboard layout",
            dueDate: "May 10", status: "Done", priority: "High", progress: 1.0,
            group: _mobileDevGroup, checklist: []),
        ProductTask(title: "Profile screen", description: "User profile and settings entry",
            dueDate: "May 12", status: "Done", priority: "Low", progress: 1.0,
            group: _mobileDevGroup, checklist: []),
        ProductTask(title: "Settings screen", description: "App preferences and account",
            dueDate: "May 15", status: "To Do", priority: "Medium", progress: 0,
            group: _mobileDevGroup, checklist: []),
        ProductTask(title: "Dark mode", description: "Theme toggle and dark palette",
            dueDate: "May 18", status: "To Do", priority: "Low", progress: 0,
            group: _mobileDesignGroup, checklist: []),
        ProductTask(title: "Animations", description: "Micro-interactions across screens",
            dueDate: "May 20", status: "To Do", priority: "Low", progress: 0,
            group: _mobileDesignGroup, checklist: []),
        ProductTask(title: "Handoff to dev", description: "Final design handoff and specs",
            dueDate: "May 22", status: "To Do", priority: "Medium", progress: 0,
            group: _mobileDesignGroup, checklist: []),
        ProductTask(title: "QA sign-off", description: "Final QA pass before release",
            dueDate: "May 25", status: "To Do", priority: "High", progress: 0,
            group: _mobileDevGroup, checklist: []),
      ],
    ),
  ];

  // ── "Create New Project" popup ───────────────────────────────────────────
  void _showCreateDialog() {
    final TextEditingController nameController = TextEditingController();
    DateTime? selectedDate; // holds the picked date

    showDialog(
      context: context,
      builder: (context) {
        // StatefulBuilder lets the dialog rebuild when the date changes
        // without rebuilding the whole page
        return StatefulBuilder(
          builder: (context, setDialogState) {
            return AlertDialog(
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(20),
              ),
              title: const Text(
                "New Project",
                style: TextStyle(fontWeight: FontWeight.bold),
              ),
              content: Column(
                mainAxisSize: MainAxisSize.min, // dialog only as tall as needed
                children: [

                  // Project name field
                  TextField(
                    controller: nameController,
                    decoration: InputDecoration(
                      hintText: "Project name",
                      filled: true,
                      fillColor: const Color(0xFFF2F4F7),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                        borderSide: BorderSide.none,
                      ),
                    ),
                  ),

                  const SizedBox(height: 14),

                  // Date picker row
                  GestureDetector(
                    onTap: () async {
                      // Opens the system calendar popup
                      final picked = await showDatePicker(
                        context: context,
                        initialDate:
                        DateTime.now().add(const Duration(days: 14)),
                        firstDate: DateTime.now(),
                        lastDate: DateTime.now()
                            .add(const Duration(days: 365 * 2)),
                      );
                      if (picked != null) {
                        // Update dialog UI to show chosen date
                        setDialogState(() => selectedDate = picked);
                      }
                    },
                    child: Container(
                      width: double.infinity,
                      padding: const EdgeInsets.symmetric(
                          horizontal: 16, vertical: 14),
                      decoration: BoxDecoration(
                        color: const Color(0xFFF2F4F7),
                        borderRadius: BorderRadius.circular(12),
                      ),
                      child: Row(
                        children: [
                          const Icon(Icons.calendar_today,
                              size: 16, color: Colors.grey),
                          const SizedBox(width: 10),
                          Text(
                            selectedDate != null
                                ? "${selectedDate!.day}/${selectedDate!.month}/${selectedDate!.year}"
                                : "Pick a deadline",
                            style: TextStyle(
                              color: selectedDate != null
                                  ? Colors.black
                                  : Colors.grey,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
              actions: [
                TextButton(
                  onPressed: () => Navigator.pop(context), // cancel
                  child: const Text("Cancel",
                      style: TextStyle(color: Colors.grey)),
                ),
                ElevatedButton(
                  onPressed: () {
                    final name = nameController.text.trim();
                    if (name.isEmpty) return; // don't create nameless projects

                    // Add the new project to the list and rebuild the page.
                    // Starts with no tasks and no groups — once the AI
                    // generation feature is wired in, this is where
                    // Project.fromAIGenerated(...) would be called instead.
                    setState(() {
                      _projects.add(Project(
                        title: name,
                        deadline: selectedDate, // null if user skipped date
                        tasks: [],  // blank by default — user adds tasks inside
                        groups: [], // blank by default — AI or user adds groups
                      ));
                    });

                    Navigator.pop(context); // close dialog
                  },
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.blue,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                  child: const Text("Create",
                      style: TextStyle(color: Colors.white)),
                ),
              ],
            );
          },
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF2F4F7),
      endDrawer: CustomNavigationDrawer(activePage: 'Dashboard'),
      body: Stack(
        children: [

          // ── Scrollable content ────────────────────────────────────────
          SafeArea(
            child: SingleChildScrollView(
              padding: const EdgeInsets.fromLTRB(20, 20, 20, 100),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [

                  // ── Header row ──────────────────────────────────────────
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: const [
                          Text(
                            "Projects",
                            style: TextStyle(
                              fontSize: 32,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                          SizedBox(height: 4),
                          Text(
                            "Manage and track your ongoing work",
                            style: TextStyle(
                                fontSize: 14, color: Colors.grey),
                          ),
                        ],
                      ),
                      Container(
                        width: 44,
                        height: 44,
                        decoration: const BoxDecoration(
                          color: Colors.blue,
                          shape: BoxShape.circle,
                        ),
                        child: IconButton(
                          icon: const Icon(Icons.menu,
                              color: Colors.white, size: 20),
                          onPressed: () {
                            // TODO: hook up drawer later
                          },
                        ),
                      ),
                    ],
                  ),

                  const SizedBox(height: 28),

                  const Text(
                    "Active Projects",
                    style: TextStyle(
                        fontSize: 20, fontWeight: FontWeight.bold),
                  ),

                  const SizedBox(height: 16),

                  // ── Project cards ───────────────────────────────────────
                  Column(
                    children: _projects
                        .map((project) => ProjectCard(
                      project: project,
                      // onUpdate triggers setState here so the card
                      // re-renders after returning from detail page
                      onUpdate: () => setState(() {}),
                    ))
                        .toList(),
                  ),
                ],
              ),
            ),
          ), // end SafeArea

          // ── Fixed bottom button — outside SafeArea so it pins to true screen bottom ──
          Positioned(
            left: 20,
            right: 20,
            bottom: 20,
            child: SizedBox(
              height: 54,
              child: ElevatedButton(
                onPressed: _showCreateDialog, // opens the popup
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.blue,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(14),
                  ),
                  elevation: 4,
                ),
                child: const Text(
                  "+ Create New Project",
                  style: TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.w600,
                    color: Colors.white,
                  ),
                ),
              ),
            ),
          ),

        ],
      ),
    );
  }
}